[tool.poetry]
name = "spammish"
version = "0.1.0"
description = "Spammish Accounts"

license = "GPLv2+"

authors = [
  "Fedora Infrastructure <admin@fedoraproject.org>"
]

readme = "README.md"
keywords = ["web", "fedora"]
repository = "http://github.com/fedora-infra/spammish"
homepage = "http://github.com/fedora-infra/spammish"

include = [
    "tox.ini",
    "*.example",
    "babel.cfg",
    "docs/*",
    "docs/*/*",
    "tests/*",
    "tests/*/*",
]

classifiers = [
    "Environment :: Web Environment",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1"
flask-healthz = "^0.0.1"
whitenoise = "^5.0.1"
gunicorn = {version = "^20.0", optional = true}
flask_mod_auth_gssapi = "^0.1.0"
python-freeipa = "^1.0.6"
flask-wtf = "^0.14.3"
requests_gssapi = "^1.2.2"
flask-talisman = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-mock = "^3.0.0"
bandit = "^1.6"
black = "^19.10b0"
flake8 = "^3.7"
isort = "^5.1"
coverage = {extras = ["toml"], version = "^5.2"}
liccheck = "^0.4.2"
sphinx = "^3.0"
beautifulsoup4 = "^4.9"
rstcheck = "^3.3.1"
safety = "^1.10.3"

[tool.poetry.extras]
deploy = ["gunicorn"]

[tool.isort]
profile = "black"
lines_after_imports = 2
force_alphabetical_sort_within_sections = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
source = ["spammish"]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
omit = [
    "spammish/__init__.py"
]


[tool.towncrier]
package = "spammish"
filename = "docs/release_notes.rst"
directory = "news/"
title_format = "v{version}"
issue_format = "{issue}"
template = "news/_template.rst"
underlines = "=^-"
wrap = true
all_bullets = true

  [[tool.towncrier.type]]
  directory = "bic"
  name = "Backwards Incompatible Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dependency"
  name = "Dependency Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bug"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dev"
  name = "Development Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "docs"
  name = "Documentation Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "other"
  name = "Other Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "author"
  name = "Contributors"
  showcontent = true


[tool.liccheck]
authorized_licenses = [
  "bsd",
  "new bsd",
  "simplified bsd",
  "apache",
  "apache 2.0",
  "apache software",
  "gnu lgpl",
  "gpl v2",
  "GNU General Public License v2 or later (GPLv2+)",
  "gpl v3",
  "lgpl with exceptions or zpl",
  "isc",
  "isc license (iscl)",
  "mit",
  "python software foundation",
  "zpl 2.1",
  "mpl-2.0",
  "lgpl",
]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
