---
- name: Install RPM packages
  dnf:
    name:
      - git
      - vim
      - poetry
      - python3-flask
      - python3-pip
      - tox
      - fedora-messaging
      - "@Development Tools"
      - tmux
      - libffi-devel
      - krb5-devel
    state: present

- name: install python deps with poetry
  shell: /srv/venv/bin/poetry install
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/spammish/

- name: Restore SELinux contexts
  command: restorecon -irv /srv/

- name: Install the .bashrc
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Install the configuration file
  copy:
    src: spammish.cfg
    dest: /home/vagrant/spammish.cfg
    owner: vagrant
    group: vagrant

- name: Install the WSGI script
  file:
    state: link
    src: /home/vagrant/spammish/deploy/spammish.wsgi
    path: /srv/spammish.wsgi

- name: Restart Apache
  systemd:
    state: restarted
    name: httpd
